app/components/map/Map.tsx, app/components/map/_MapComponent.client.tsx, app/main.css, app/root.tsx, app/routes/_index.tsx, package-lock.json, package.json
* Added a dependency for Leaflet libraries
* Created `_MapComponent.client` client-side rendered component for viewing the map (used inside `Map.tsx`)
* Updated routing and created `_index.tsx` route for code separation
* Map viewed in full screen
=> Leaflet map integration

app/components/map/Map.tsx, app/components/map/_MapComponent.client.tsx
This implements historical satellite images that can be selected as map layers.
=> Historical satellite images

app/components/controls/Controls.tsx, app/components/controls/fabs/Fabs.tsx, app/components/controls/searchbar/SearchBar.tsx, app/components/map/Map.tsx, app/components/map/_MapComponent.client.tsx, app/main.css, app/root.tsx, app/theme.ts, package-lock.json, package.json
- Uses a simple theme with color variables taken from the Figma design
- Added placeholder buttons and search bar on top of the Leaflet map
=> Initial frontend elements

app/components/controls/searchbar/SearchBar.tsx
Add location search functionality.
=> Location search

app/components/map/_MapComponent.client.tsx, app/components/map/layers/ConservationLayer.tsx, app/components/map/layers/ReportLayer.tsx, app/components/map/layers/SpeciesLayer.tsx, app/components/map/markers/CustomMarker.tsx, package-lock.json, package.json
* Added `ConservationLayer.tsx` which renders conservation areas from SYKE api
* Added `ReportLayer.tsx` which renders markers in the Leaflet map (currently uses hard coded list of coordinates)
* Added `SpeciesLayer.tsx` which renders markers on the Leaflet map (currently uses hard coded list of coordinates)
* `_MapComponent.client.tsx` uses these layers inside `LayersControl`
=> Conservation, report and species layers

app/components/controls/fabs/Fabs.tsx, app/components/map/_MapComponent.client.tsx
The map now zooms in to user location when the viewCentered button is pressed.
=> feat(map): add functionality to viewCentered -button

app/components/controls/fabs/Fabs.tsx, app/components/map/_MapComponent.client.tsx
The map now zooms in to user location when the locate user -button is pressed.
=> Functionality to locate user -button added

app/routes/createObservation.tsx, app/routes/observations.tsx
Created endpoints for displaying observations from an area and creating an observation.
=> Endpoints for incident reports

app/components/controls/Controls.tsx, app/components/controls/indicators/ProgressIndicator.tsx, app/components/map/MapBounds.tsx, app/components/map/_MapComponent.client.tsx, app/components/map/layers/ReportLayer.tsx, app/components/map/layers/SpeciesLayer.tsx
- User feedback is now given when the application is fetching data about sightings.
https://github.com/user-attachments/assets/cbc0d12b-1c60-45ca-8038-9ea75c10933a
- Sighting and observation marker clusters now have different visual appearance:
=> UX improvements

app/utils/db.server.ts, package-lock.json, package.json
=> Fix top-level await

app/components/controls/Controls.tsx, app/components/controls/datePickers/DatePickers.tsx, app/components/controls/drawer/Drawer.tsx, app/components/controls/slider/DateSlider.tsx, app/components/map/_MapComponent.client.tsx
- formats the date correctly that is selected from DatePickers with `dayjs().format()` instead of `toISOString()` which resulted in incorrect date formatting after adding the DatePickers. 
- Added DateSlider value prop to be changed in DatePickers
DateSlider value prop in DatePickers component might need further refactoring, this pull request only fixes the issue of the date values not changing correctly, Refactoring for the functionality of the DateSlider will be added separately.
=> Date fixes

package-lock.json, package.json
This is to test the newly made Docker action from #117.
=> Test release

app/components/map/MapBounds.tsx, app/components/map/_MapComponent.client.tsx, app/components/map/layers/ReportLayer.tsx, app/routes/observations.tsx
ReportLayer now utilizes observations.tsx endpoint instead of mock data.
=> Incident Data Markers

app/components/map/_MapComponent.client.tsx
Added missing attributes laji and syke to map.
=> Map attributes

app/routes/admin._index.tsx, app/routes/admin.logout.tsx, app/utils/db.server.ts, app/utils/s3.server.ts
Improve admin interface with logout button and deletion confirmation.
=> Admin improvements

app/components/controls/Controls.tsx, app/components/controls/drawer/Drawer.tsx, app/components/controls/fabs/Fabs.tsx, app/components/controls/indicators/InfoBox.tsx, app/components/controls/searchbar/SearchBar.tsx, app/components/controls/slider/DateSlider.tsx
This fixes all event propagation problems and slider dragging. Also improves search names.
=> Fix events

app/utils/s3.server.ts
Fix S3 credentials not being present.
=> AWS fix S3

app/entry.client.tsx, app/entry.server.tsx, app/root.tsx, app/utils/i18n.ts, app/utils/i18next.server.ts, app/utils/locales/fi/translation.json, package-lock.json, package.json, vite.config.ts
Adds localization using remix-i18next.
How to use in frontend:
1. add translation to /app/utils/locales/fi/translations.json file for example `{
"searchBar": "Etsi paikkaa"
}`
2. use the "`useTranslation`" hook in a function for example: 
```
import { useTranslation } from "react-i18next";
export default function SearchBar() {
let { t } = useTranslation();
return 
...
placeholder={t("searchBar")}
...
}
```
For more specific examples go to: https://remix.run/resources/remix-i18next
=> Localization

app/components/map/Map.tsx, app/components/map/MapBounds.tsx, app/components/map/_MapComponent.client.tsx, app/components/map/layers/ReportLayer.tsx, app/components/map/layers/SpeciesLayer.tsx, app/components/map/loading/LoadingScreen.tsx, app/components/map/markers/CustomMarker.tsx, app/root.tsx
- Added simple loading screen when loading the app and the map
- Pausing fetching when clicking a marker
=> Usability improvements

app/components/controls/Controls.tsx
This is a very huge change to fix the slider to show the correct date when user opens the satellite view without adding any dates first.
=> Fix slider
